Experimental CMake-based build system
This patch adds an experimental (and unsupported, for now) CMake-based
build-system for Seastar.

Having the CMake files available in the tree should make it easier for
us to reach feature-parity with the existing build system and switch
over exclusively to CMake.

Most of the features of `configure.py` and `test.py` scripts work in an
at least preliminary (if not complete) fashion.
However, some features of those scripts are deprecated and have not been
translated over.

This version of the build supports both the debug and release
configurations, though each build directory with CMake has a single
configuration. The unit-test suite passes, and all included tests
compile. Linking a client application against Seastar as described below
works as expected.

The primary way to build an application against Seastar with this build
system is to clone the Seastar repository and then, in your own
application's CMakeLists.txt file, to link against the imported target.
Nothing else should be necessary.

add_subdirectory (${MY_SEASTAR_CLONE_DIR})
add_executable (my_app my_app_source.cc)
target_link_libraries (my_app Seastar::seastar)

In case your application does not build with CMake, a pkg-config
file (`seastar.pc`) is built with the `pkg-config` target in the build
directory.

Quick start:
$ mkdir build-cmake
$ cd build-cmake
$ cmake -DCMAKE_BUILD_TYPE=Release -G Ninja ..
$ ninja-build
$ ctest -j4 # Run tests.
$ ctest -j4 -R allocator # Run tests matching the pattern.

Special thanks to Noah Watkins for his contributions to this initial
CMake work, including:

- Only query for the link pool size if we're using the Ninja generator.
- Simplify handling of Protobuf.
- Remove unused compiler flag.
- Only build tests and applications if requested.
- Support CMake 2.8.
- Specify source files in the "root" `CMakeLists.txt` file instead of
  having many files spread around sub-directories.

Future work:

- Replacement `configure.py` and `test.py` scripts that call into the
  CMake equivalents.

Known issues:

- DPDK compilation fails:

CC scheduler_pmd.o
/home/jhaberku/src/seastar/dpdk/drivers/crypto/scheduler/scheduler_pmd.c:39:10: fatal error: rte_reorder.h: No such file or directory

Signed-off-by: Jesse Haber-Kucharsky <jhaberku@scylladb.com>
Message-Id: <1b9bb12de1db5413df137b32b9389416b56b15df.1524237504.git.jhaberku@scylladb.com>