core: weak_ptr, weakly_referencable: implement empty default constructor
This fixes an error we see with gcc 9 on Fedora 31.  The gist of it is:
`'seastar::weak_ptr<T>::weak_ptr() noexcept [with T = myclass]' is implicitly deleted because its exception-specification does not match the implicit exception-specification ''`

boost::intrusive::list_member_hook is not specified as noexcept and
gcc 9.3.1 appears to implicitly delete the constructor
in contrust to gcc 10.1.1, clang 9.0.1, and clang 10.0.0 that allow
defining the constructor as noexcept = default; even if some of the members'
default constructors are potentially throwing.

Implementing the constructor body, rather than using the implicit `= default`
will end up in the same behavior, of a crash if the default constructed member throws,
but in this case, we presume that boost::intrusive::list_member_hook has no reason
to throw when default constructed.

```
$ g++ --version
g++ (GCC) 9.3.1 20200408 (Red Hat 9.3.1-2)

$ /usr/bin/g++  -DFMT_SHARED -DSEASTAR_API_LEVEL=3 -DSEASTAR_HAS_MEMBARRIER -DSEASTAR_HAVE_ASAN_FIBER_SUPPORT -DSEASTAR_HAVE_HWLOC -DSEASTAR_HAVE_LZ4_COMPRESS_DEFAULT -DSEASTAR_HAVE_NUMA -DSEASTAR_TESTING_MAIN -DSEASTAR_THREAD_STACK_GUARDS -DSEASTAR_TYPE_ERASE_MORE -I../../tests/unit -I../../src -I../../include -Igen/include -O1   -fvisibility=hidden -UNDEBUG -Wall -Werror -Wno-array-bounds -Wno-error=deprecated-declarations -gz -I/opt/scylladb/include -std=gnu++17 -U_FORTIFY_SOURCE -Wno-maybe-uninitialized -DSEASTAR_SSTRING -Wno-error=unused-result -fstack-clash-protection -MD -MT tests/unit/CMakeFiles/test_unit_weak_ptr.dir/weak_ptr_test.cc.o -MF tests/unit/CMakeFiles/test_unit_weak_ptr.dir/weak_ptr_test.cc.o.d -o tests/unit/CMakeFiles/test_unit_weak_ptr.dir/weak_ptr_test.cc.o -c ../../tests/unit/weak_ptr_test.cc
../../tests/unit/weak_ptr_test.cc:30:20: error: static assertion failed
   30 | static_assert(std::is_nothrow_default_constructible_v<weak_ptr<int>>);
      |               ~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../../tests/unit/weak_ptr_test.cc:35:20: error: static assertion failed
   35 | static_assert(std::is_nothrow_default_constructible_v<weakly_referencable<myclass>>);
      |               ~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../../tests/unit/weak_ptr_test.cc: In member function 'void test_weak_ptr_is_empty_when_default_initialized::test_method()':
../../tests/unit/weak_ptr_test.cc:38:23: error: use of deleted function 'seastar::weak_ptr<T>::weak_ptr() [with T = myclass]'
   38 |     weak_ptr<myclass> wp;
      |                       ^~
In file included from ../../tests/unit/weak_ptr_test.cc:26:
../../include/seastar/core/weak_ptr.hh:50:5: note: 'seastar::weak_ptr<T>::weak_ptr() noexcept [with T = myclass]' is implicitly deleted because its exception-specification does not match the implicit exception-specification ''
   50 |     weak_ptr() noexcept = default;
      |     ^~~~~~~~
```

Signed-off-by: Benny Halevy <bhalevy@scylladb.com>
Message-Id: <20200614142410.283346-1-bhalevy@scylladb.com>