drop unused parameters
to silence warnings from GCC-11, like:

seastar/include/seastar/core/future.hh:1357:42: error: unused parameter
‘m’ [-Werror=unused-parameter]

Signed-off-by: Kefu Chai <tchaikov@gmail.com>
Message-Id: <20220520023211.3162590-1-tchaikov@gmail.com>