rpc: init all member variables
unfortunately, this is a false alarm, as gate has a default constructor.

but would be nice to silence the warning from GCC-12:

../third-party/seastar/include/seastar/rpc/rpc_impl.hh: In instantiation of ‘auto seastar::rpc::protocol<Serializer, MsgType>::register_handler(MsgType, seastar::scheduling_group, Func&&) [with Func = server_runner::server_runner(const seastar::socket_address&)::<lam$
 ../third-party/seastar/include/seastar/rpc/rpc_impl.hh:683:28:   required from ‘auto seastar::rpc::protocol<Serializer, MsgType>::register_handler(MsgType, Func&&) [with Func = server_runner::server_runner(const seastar::socket_address&)::<lambda(init_rings_request)>$
 ../src/demos/rings.cc:202:26:   required from here
 ../third-party/seastar/include/seastar/rpc/rpc_impl.hh:676:22: error: missing initializer for member ‘seastar::rpc::rpc_handler::use_gate’ [-Werror=missing-field-initializers]
   676 |     register_receiver(t, rpc_handler{sg, make_copyable_function(std::move(recv))});
       |
       ~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Signed-off-by: Kefu Chai <tchaikov@gmail.com>