chunked_fifo: const_iterator: use the base class ctor
Need to be using `basic_iterator<const T>`
rather than `basic_iterator<T>`

Otherwise, we get the following compilation error:
```
/home/bhalevy/dev/seastar/include/seastar/core/chunked_fifo.hh:164:15: error: using declaration refers into 'basic_iterator<int>::', which is not a base class of 'const_iterator'
        using basic_iterator<T>::basic_iterator;
              ^~~~~~~~~~~~~~~~~~~
```

Added a unit test that doesn't build without the fix.

Signed-off-by: Benny Halevy <bhalevy@scylladb.com>