drop unused parameters
to silence warnings from Clang-14, like

seastar/include/seastar/core/transfer.hh:69:38: error: unused parameter 'to' [-Werror,-Wunused-parameter]
 transfer_pass2(Alloc& a, T* from, T* to,
                                      ^
 1 error generated.

these are leftovers of 551c144757d092f2ab7c449042a8bc9af66c5d26

Signed-off-by: Kefu Chai <tchaikov@gmail.com>