build: Fix chevrons imbalance in liburing_libs
Commit be3fc0ee (build: use URING_LIBRARIES for liburing_libs in .pc
file) broke the brackets harmony in one of the variables. This comes
unnoticed when building seastar, but breaks scylla in a weird manner:

./build/dev/gen/api/api-doc/endpoint_snitch_info.json.hh:14:10: fatal error: 'seastar/core/sstring.hh' file not found

Signed-off-by: Pavel Emelyanov <xemul@scylladb.com>