Revert "util/source_location-compat: mark `source_location::current()` consteval"
```
../src/seastar/include/seastar/util/log.hh:191:51: error: cannot take address of consteval function 'current' outside of an immediate invocation
        format_info(compat::source_location loc = compat::source_location::current()) noexcept
                                                  ^
../src/seastar/include/seastar/util/source_location-compat.hh:50:21: note: declared here
    source_location current(const char* file = __builtin_FILE(), const char* func = __builtin_FUNCTION(), int line = __builtin_LINE(), int col = 0) noexcept {
```

This reverts commit 550da0e6750a625a171934240c9f7842ab05bc58.

Signed-off-by: Matan Breizman <mbreizma@redhat.com>