reactor: Add missing CentOS 7.2 dependency systemtap-sdt-devel
This patch added systemtap-sdt-devel package to install-dependencies.sh
for centos.

Error message when building on centos7.2:
  [2/169] CXX build/release/core/reactor.o
  core/reactor.cc:85:21: fatal error: sys/sdt.h: No such file or directory

Env:
  # cat /etc/redhat-release
  CentOS Linux release 7.2.1511 (Core)

Signed-off-by: Javeme Lee <javaloveme@gmail.com>
Message-Id: <20170104145213.44721-1-javaloveme@gmail.com>