Revert "scheduling groups: Adding per scheduling group data support"
This reverts commit 6282ce09d6e2cd80c85f0cc1d8073cbfd07904f6. It does
not compile with -Werror=unused-result:

FAILED: CMakeFiles/seastar.dir/src/core/reactor.cc.o
/usr/lib64/ccache/g++  -DFMT_SHARED -DSEASTAR_API_LEVEL=2 -DSEASTAR_HAS_MEMBARRIER -DSEASTAR_HAVE_ASAN_FIBER_SUPPORT -DSEASTAR_HAVE_GCC6_CONCEPTS -DSEASTAR_HAVE_HWLOC -DSEASTAR_HAVE_LZ4_COMPRESS_DEFAULT -DSEASTAR_HAVE_NUMA -DSEASTAR_TYPE_ERASE_MORE -DSEASTAR_USE_STD_OPTIONAL_VARIANT_STRINGVIEW -I/home/avi/scylla-maint/seastar/include -Igen/include -I/home/avi/scylla-maint/seastar/src -Igen/src -O1   -std=gnu++17 -U_FORTIFY_SOURCE -Wno-maybe-uninitialized -Werror=unused-result -fvisibility=hidden -UNDEBUG -Wall -Werror -Wno-error=deprecated-declarations -gz -Wno-error -march=westmere -O1 -fconcepts -MD -MT CMakeFiles/seastar.dir/src/core/reactor.cc.o -MF CMakeFiles/seastar.dir/src/core/reactor.cc.o.d -o CMakeFiles/seastar.dir/src/core/reactor.cc.o -c /home/avi/scylla-maint/seastar/src/core/reactor.cc
distcc[702] ERROR: compile /home/avi/scylla-maint/seastar/src/core/reactor.cc on loki/3,lzo failed
/home/avi/scylla-maint/seastar/src/core/reactor.cc: In lambda function:
/home/avi/scylla-maint/seastar/src/core/reactor.cc:6246:46: error: ignoring returned value of type 'seastar::future<>', declared with attribute nodiscard [-Werror=unused-result]
/home/avi/scylla-maint/seastar/src/core/reactor.cc:6177:1: note: in call to 'seastar::future<> seastar::reactor::destroy_scheduling_group(seastar::scheduling_group)', declared here
In file included from /home/avi/scylla-maint/seastar/include/seastar/core/seastar.hh:45,
                 from /home/avi/scylla-maint/seastar/include/seastar/core/reactor.hh:24,
                 from /home/avi/scylla-maint/seastar/src/core/reactor.cc:31:
/home/avi/scylla-maint/seastar/include/seastar/core/future.hh:837:21: note: 'seastar::future<>' declared here
cc1plus: some warnings being treated as errors
ninja: build stopped: subcommand failed.