map_reduce: futurize_invoke reducer
Starting from Seastar_API_LEVEL 5 we need to call futurize_invoke
if the mapper doesn't return a future<std::tuple<T>>.

Otherwise, we hit the following error when compiling futures_test
with the test case added in the following patch:
```
../../tests/unit/futures_test.cc:507:6:   required from here
../../include/seastar/core/map_reduce.hh:108:42: warning: ‘auto seastar::futurize_apply(Func&&, Args&& ...) [with Func = test_map_reduce_simple::run_test_case()::<lambda(auto:83&)> [with auto:83 = long int]::<lambda(long int)>&; Args = {long int}]’ is deprecated: Use futurize_invoke for varargs [-Wdeprecated-declarations]
  108 |                     return futurize_apply(*r_ptr, std::move(f.get()));
...
../../tests/unit/futures_test.cc:520:6:   required from here
../../include/seastar/core/future.hh:2177:11: error: no type named ‘type’ in ‘struct std::invoke_result<test_map_reduce_tuple::run_test_case()::<lambda(auto:84&, auto:85&)> [with auto:84 = long int; auto:85 = long int]::<lambda(std::tuple<long int, long int>)>&, long int&&, long int&&>’
 2177 |     using futurator = futurize<std::invoke_result_t<Func, Args&&...>>;
      |           ^~~~~~~~~
```
Signed-off-by: Benny Halevy <bhalevy@scylladb.com>