tests: Fix NDEBUG build
When building with NDEBUG assert becomes nothing and clang-23 complains
about unused globals.

```
/build/seastar/tests/perf/perf_tests_perf.cc:142:12: error: variable 'hook_1_count' set but not used [-Werror,-Wunused-but-set-global]
  142 | static int hook_1_count = 0, hook_2_count = 1;
      |            ^
/build/seastar/tests/perf/perf_tests_perf.cc:142:30: error: variable 'hook_2_count' set but not used [-Werror,-Wunused-but-set-global]
  142 | static int hook_1_count = 0, hook_2_count = 1;
```

Mark them as maybe_unused to resolve this issue.

Closes scylladb/seastar#3554