configure.py: add -Wno-sign-compare to compile Boost.Test with gcc-7
To compile Seastar with boost-1.63/g++-7, we need to disable 'sign-compare'
warning.

Following is compile error message:

tests/loading_cache_test.cc:118:9:   required from here
/opt/scylladb/include/boost/test/tools/old/impl.hpp:107:17: error: comparison between signed and unsigned integer expressions [-Werror=sign-compare]
     return left == right;
                 ~~~~~^~~~~~~~

Signed-off-by: Takuya ASADA <syuu@scylladb.com>
Message-Id: <1508457533-13267-1-git-send-email-syuu@scylladb.com>