reactor: fix buildability with SEASTAR_NO_EXCEPTION_HACK
This patch addresses the following FTBFS:

```
../src/seastar/src/core/reactor.cc:3522:7: error: no matching constructor for initialization of 'program_options::value<bool>'
    , enable_glibc_exception_scaling_workaround(*this, program_options::unused{})
      ^                                         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../src/seastar/include/seastar/util/program-options.hh:445:5: note: candidate constructor not viable: requires 1 argument, but 2 were provided
    value(value&&) = default;
    ^
../src/seastar/include/seastar/util/program-options.hh:409:7: note: candidate constructor (the implicit copy constructor) not viable: requires 1 argument, but 2 were provided
class value : public basic_value {
      ^
../src/seastar/include/seastar/util/program-options.hh:442:5: note: candidate constructor not viable: requires 3 arguments, but 2 were provided
    value(option_group& group, std::string name, unused)
    ^
../src/seastar/include/seastar/util/program-options.hh:437:5: note: candidate constructor not viable: requires 4 arguments, but 2 were provided
    value(option_group& group, std::string name, std::optional<T> default_value, std::string description)
```

Signed-off-by: Radosław Zarzyński <rzarzyns@redhat.com>
Message-Id: <20220316124008.641264-1-rzarzyns@redhat.com>