condition-variable: use an empty loop for spinning CPU
in the release build, the body of `while` loop would be
optimized out, so replace it with an empty loop body
which is enough to keep the CPU spinning.

this change silences the warning from clang++-15:

FAILED: tests/unit/CMakeFiles/test_unit_condition_variable.dir/condition_variable_test.cc.o
/usr/bin/clang++-15 -DBOOST_TEST_DYN_LINK -DFMT_LOCALE -DFMT_SHARED -DSEASTAR_API_LEVEL=6 -DSEASTAR_BROKEN_SOURCE_LOCATION -DSEASTAR_DEBUG -DSEASTAR_DEBUG_SHARED_PTR -DSEASTAR_DEFAULT_ALLOCATOR -DSEASTAR_DEFERRED_ACTION_REQUIRE_NOEXCEPT -DSEASTAR_HAS_MEMBARRIER -DSEASTAR_HAVE_ASAN_FIBER_SUPPORT -DSEASTAR_HAVE_HWLOC -DSEASTAR_HAVE_LZ4_COMPRESS_DEFAULT -DSEASTAR_HAVE_NUMA -DSEASTAR_SCHEDULING_GROUPS_COUNT=16 -DSEASTAR_SHUFFLE_TASK_QUEUE -DSEASTAR_TESTING_MAIN -DSEASTAR_THREAD_STACK_GUARDS -DSEASTAR_TYPE_ERASE_MORE -I/var/ssd/ceph/src/seastar/tests/unit -I/var/ssd/ceph/src/seastar/src -I/var/ssd/ceph/src/seastar/include -I/var/ssd/ceph/src/seastar/build/debug/gen/include -g -U_FORTIFY_SOURCE -DSEASTAR_SSTRING -Wno-error=unused-result "-Wno-error=#warnings" -fstack-clash-protection -fsanitize=address -fsanitize=undefined -fno-sanitize=vptr -fvisibility=hidden -UNDEBUG -Wall -Werror -Wno-array-bounds -Wno-error=deprecated-declarations -gz -std=gnu++2b -MD -MT tests/unit/CMakeFiles/test_unit_condition_variable.dir/condition_variable_test.cc.o -MF tests/unit/CMakeFiles/test_unit_condition_variable.dir/condition_variable_test.cc.o.d -o tests/unit/CMakeFiles/test_unit_condition_variable.dir/condition_variable_test.cc.o -c /var/ssd/ceph/src/seastar/tests/unit/condition_variable_test.cc
/var/ssd/ceph/src/seastar/tests/unit/condition_variable_test.cc:362:17: error: variable 'q' set but not used [-Werror,-Wunused-but-set-variable]
            int q = 0;
                ^
1 error generated.

Signed-off-by: Kefu Chai <tchaikov@gmail.com>
Message-Id: <20220614132138.3489754-2-tchaikov@gmail.com>