util: mark unused parameter with [[maybe_unused]]
this helps to silence warnings from GCC-11, like:

../third-party/seastar/include/seastar/util/noncopyable_function.hh:112:60: error: unused parameter ‘args#0’ [-Werror=unused-parameter]
  112 |     static Ret empty_call(const noncopyable_function*, Args... args) {
      |                                                        ~~~~^~~~~~~~

Signed-off-by: Kefu Chai <tchaikov@gmail.com>
Message-Id: <20220520023211.3162590-2-tchaikov@gmail.com>