coroutines/all: ensure the template argument deduction work with clang-15
coroutine::all() needs one or more template argument, so let's enforce
this contraint in the deduction guide. without this change, we'd have
following compiling failure with clang-15:

In file included from /home/kefu/d/ceph/src/seastar/tests/unit/coroutines_test.cc:22:
In file included from /usr/bin/../lib/gcc/x86_64-linux-gnu/12/../../../../include/c++/12/exception:168:
In file included from /usr/bin/../lib/gcc/x86_64-linux-gnu/12/../../../../include/c++/12/bits/exception_ptr.h:43:
In file included from /usr/bin/../lib/gcc/x86_64-linux-gnu/12/../../../../include/c++/12/bits/move.h:57:
/usr/bin/../lib/gcc/x86_64-linux-gnu/12/../../../../include/c++/12/type_traits:2154:7: error: static_assert failed due to requirement 'sizeof...(_Types) != 0' "At least one type is required"
      static_assert(sizeof...(_Types) != 0, "At least one type is required");
      ^             ~~~~~~~~~~~~~~~~~~~~~~
/usr/bin/../lib/gcc/x86_64-linux-gnu/12/../../../../include/c++/12/type_traits:2606:5: note: in instantiation of template class 'std::aligned_union<1>' requested here
    using aligned_union_t = typename aligned_union<_Len, _Types...>::type;
    ^
/home/kefu/d/ceph/src/seastar/include/seastar/coroutine/all.hh:143:27: note: in instantiation of template type alias 'aligned_union_t' requested here
        using type = std::aligned_union_t<1, intermediate_task<idx>...>;
                          ^
/home/kefu/d/ceph/src/seastar/include/seastar/coroutine/all.hh:147:45: note: in instantiation of template class 'seastar::coroutine::all<>::generate_aligned_union<std::integer_sequence<unsigned long>>' requested here
    using continuation_storage_t = typename generate_aligned_union<std::make_index_sequence<std::tuple_size_v<tuple>>>::type;
                                            ^
/home/kefu/d/ceph/src/seastar/tests/unit/coroutines_test.cc:301:28: note: in instantiation of template class 'seastar::coroutine::all<>' requested here
    auto [a, b] = co_await coroutine::all(
                           ^
/home/kefu/d/ceph/src/seastar/tests/unit/coroutines_test.cc:318:14: error: type 'seastar::coroutine::all<>::value_tuple' (aka 'tuple<>') decomposes into 0 elements, but 6 names were provided
        auto [a, b, c, d, e, f] = co_await coroutine::all(
             ^

Signed-off-by: Kefu Chai <tchaikov@gmail.com>
Message-Id: <20220529121313.4106274-1-tchaikov@gmail.com>