Revert "sstring: restore compatibility with std::string"
This reverts commit 480aaf848e70d9d5ac6879aae0785148b3189e37. Fails on
clang with

/home/circleci/project/include/seastar/core/sstring.hh:699:32: error: unknown warning group '-Wstringop-overread', ignored [-Werror,-Wunknown-warning-option]