Revert "deleter: prevent early memory free caused by deleter append."
This reverts commit 168a7f5de962ca37464b8ca7b6ef7db809b3ae83, does not
build:

../../tests/unit/deleter_test.cc:19:1: error: "/*" within comment [-Werror=comment]
 /* Copyright (C) 2019 Lightbits Labs Ltd. - All Rights Reserved