http/api_docs: always call parent constructor
because `api_docs` is derived from `json::json_base`, and 1) its copy
constructor is explicitly defined, 2) `json::json_base` 's copy
constructor is disabled, we need to initialize the base class.

this also silence the warning like

seastar/include/seastar/http/api_docs.hh:81:5: error: base class ‘struct
seastar::json::json_base’ should be explicitly initialized in the copy
constructor [-Werror=extra]
     api_docs(const api_docs & e) {
     ^~~~~~~~

Signed-off-by: Kefu Chai <tchaikov@gmail.com>
Message-Id: <20190816102457.13297-2-tchaikov@gmail.com>