Revert "gate: add gate::holder", does not build.
This reverts commit d3b7541337107bdb4963bdb1f1f99270d0441b9d. It fails to
build:

FAILED: tests/unit/CMakeFiles/test_unit_closeable.dir/closeable_test.cc.o
/usr/bin/g++  -DBOOST_TEST_DYN_LINK -DFMT_LOCALE -DFMT_SHARED -DSEASTAR_API_LEVEL=6 -DSEASTAR_HAS_MEMBARRIER -DSEASTAR_HAVE_ASAN_FIBER_SUPPORT -DSEASTAR_HAVE_HWLOC -DSEASTAR_HAVE_LZ4_COMPRESS_DEFAULT -DSEASTAR_HAVE_NUMA -DSEASTAR_TESTING_MAIN -I../../tests/unit -I../../src -I../../include -Igen/include -O2 -g -DNDEBUG   -std=c++20 -U_FORTIFY_SOURCE -Wno-maybe-uninitialized -DSEASTAR_SSTRING -Wno-error=unused-result -fvisibility=hidden -UNDEBUG -Wall -Werror -Wno-array-bounds -Wno-error=deprecated-declarations -gz -MD -MT tests/unit/CMakeFiles/test_unit_closeable.dir/closeable_test.cc.o -MF tests/unit/CMakeFiles/test_unit_closeable.dir/closeable_test.cc.o.d -o tests/unit/CMakeFiles/test_unit_closeable.dir/closeable_test.cc.o -c ../../tests/unit/closeable_test.cc
../../tests/unit/closeable_test.cc: In lambda function:
../../tests/unit/closeable_test.cc:279:14: error: no matching function for call to 'parallel_for_each(boost::integer_range<int>, gate_holder_parallel_copy_test::run_test_case()::<lambda(int&)>::<lambda(seastar::gate&)>::<lambda(int)>)'
  279 |             });
      |              ^
In file included from ../../tests/unit/closeable_test.cc:31:
../../include/seastar/core/loop.hh:547:1: note: candidate: 'template<class Iterator, class Func>  requires requires(Func f, Iterator i) {{f(*i++)} -> decltype(auto) [requires std::same_as<<placeholder>, seastar::future<void> >];} seastar::future<> seastar::parallel_for_each(Iterator, Iterator, Func&&)'
  547 | parallel_for_each(Iterator begin, Iterator end, Func&& func) noexcept {
      | ^~~~~~~~~~~~~~~~~
../../include/seastar/core/loop.hh:547:1: note:   template argument deduction/substitution failed:
../../tests/unit/closeable_test.cc:279:14: note:   deduced conflicting types for parameter 'Iterator' ('boost::integer_range<int>' and 'gate_holder_parallel_copy_test::run_test_case()::<lambda(int&)>::<lambda(seastar::gate&)>::<lambda(int)>')
  279 |             });
      |              ^
In file included from ../../tests/unit/closeable_test.cc:31:
../../include/seastar/core/loop.hh:608:1: note: candidate: 'seastar::future<> seastar::parallel_for_each(Range&&, Func&&) [with Range = boost::integer_range<int>; Func = gate_holder_parallel_copy_test::run_test_case()::<lambda(int&)>::<lambda(seastar::gate&)>::<lambda(int)>]'
  608 | parallel_for_each(Range&& range, Func&& func) noexcept {
      | ^~~~~~~~~~~~~~~~~
../../include/seastar/core/loop.hh:608:1: note: constraints not satisfied
In file included from ../../include/seastar/core/scheduling.hh:27,
                 from ../../include/seastar/core/task.hh:25,
                 from ../../include/seastar/core/future.hh:24,
                 from ../../include/seastar/testing/test_case.hh:25,
                 from ../../tests/unit/closeable_test.cc:26:
../../include/seastar/core/loop.hh: In instantiation of 'seastar::future<> seastar::parallel_for_each(Range&&, Func&&) [with Range = boost::integer_range<int>; Func = gate_holder_parallel_copy_test::run_test_case()::<lambda(int&)>::<lambda(seastar::gate&)>::<lambda(int)>]':
../../tests/unit/closeable_test.cc:279:14:   required from here
../../include/seastar/core/loop.hh:608:1:   required by the constraints of 'template<class Range, class Func>  requires requires(Func f, Range r) {{f(*r.begin())} -> decltype(auto) [requires std::same_as<<placeholder>, seastar::future<void> >];} seastar::future<> seastar::parallel_for_each(Range&&, Func&&)'
../../include/seastar/core/loop.hh:605:1:   in requirements with 'Func f', 'Range r' [with Range = boost::integer_range<int>; Func = gate_holder_parallel_copy_test::run_test_case::._anon_291::operator()::._anon_292::operator()::._anon_293]
../../include/seastar/core/loop.hh:605:59: note: 'f((* r.begin()))' does not satisfy return-type-requirement
  605 | SEASTAR_CONCEPT( requires requires (Func f, Range r) { { f(*r.begin()) } -> std::same_as<future<>>; } )
      |                                                          ~^~~~~~~~~~~~
../../include/seastar/util/concepts.hh:26:31: note: in definition of macro 'SEASTAR_CONCEPT'
   26 | #define SEASTAR_CONCEPT(x...) x
      |                               ^
cc1plus: note: set '-fconcepts-diagnostics-depth=' to at least 2 for more detail