testing: Add missing <iostream> include to seastar_test.cc
I am in a slightly old compiler in this box, maybe this is why. Message
I see when compiling master:

distcc[2072] ERROR: compile ../../src/testing/seastar_test.cc on localhost failed
../../src/testing/seastar_test.cc: In lambda function:
../../src/testing/seastar_test.cc:79:18: error: ‘cerr’ is not a member of ‘std’
             std::cerr << "Expected \"" << expected_message << "\" but got \"" << error << '"' << std::endl;
                  ^~~~
../../src/testing/seastar_test.cc:79:18: note: ‘std::cerr’ is defined in header ‘<iostream>’; did you forget to ‘#include <iostream>’?
../../src/testing/seastar_test.cc:31:1:
+#include <iostream>

../../src/testing/seastar_test.cc:79:18:
             std::cerr << "Expected \"" << expected_message << "\" but got \"" << error << '"' << std::endl;
                  ^~~~
../../src/testing/seastar_test.cc: In lambda function:
../../src/testing/seastar_test.cc:91:18: error: ‘cerr’ is not a member of ‘std’
             std::cerr << "Expected \"" << expected_message << "\" but got \"" << error << '"' << std::endl;
                  ^~~~
../../src/testing/seastar_test.cc:91:18: note: ‘std::cerr’ is defined in header ‘<iostream>’; did you forget to ‘#include <iostream>’?

Signed-off-by: Glauber Costa <glauber@scylladb.com>
Reviewed-by: Benny Halevy <bhalevy@scylladb.com>
Message-Id: <20200417143617.3236-1-glauber@scylladb.com>