future.hh: drop unused parameters
this change silence following warning:

include/seastar/core/future.hh:645:42: error: unused parameter ‘m’ [-Werror=unused-parameter]
645 | future_state(exception_future_marker m, future_state_base&& state) noexcept : future_state_base(std::move(state)) { }

Signed-off-by: Kefu Chai <tchaikov@gmail.com>
Message-Id: <20220525161634.2926166-2-tchaikov@gmail.com>