test: futures: disable -Wself-move for GCC>=13
GCC supports `-Wself-move` now, see
https://gcc.gnu.org/onlinedocs/gcc/Warning-Options.html. so we should
disable this warning when testing self-move.

this should silence the warning from GCC 13:
```
/home/kefu/dev/scylladb/seastar/tests/unit/futures_test.cc: In member function ‘virtual seastar::future<> test_self_move::run_test_case() const’:
/home/kefu/dev/scylladb/seastar/tests/unit/futures_test.cc:78:8: error: moving ‘s1’ of type ‘seastar::future_state<std::tuple<std::unique_ptr<int, std::default_delete<int> > > >’ to itself [-Werror=self-move]
   78 |     s1 = std::move(s1); // no crash, but the value of s1 is not defined.
      |     ~~~^~~~~~~~~~~~~~~
```

Signed-off-by: Kefu Chai <kefu.chai@scylladb.com>