temporary_buffer: fix the dev build failure due to gcc bug
It was failing with the error

../include/seastar/core/temporary_buffer.hh:84:65: error: ‘<anonymous>.seastar::temporary_buffer<char>::_buffer’ may be used uninitialized in this function [-Werror=maybe-uninitialized]
     temporary_buffer(temporary_buffer&& x) noexcept : _buffer(x._buffer), _size(x._size), _deleter(std::move(x._deleter)) {
                                                               ~~^~~~~~~

After a careful reduction, I am pretty sure this is a bug in gcc
and reported https://gcc.gnu.org/bugzilla/show_bug.cgi?id=88897.

Since the warning is triggered by the use of
std::experimental::optional<temporary_buffer>, I don't see a
particularly elegant way of avoiding it. This patch just uses pragmas
around the unlucky code.

Signed-off-by: Rafael Ávila de Espíndola <espindola@scylladb.com>
Message-Id: <20190121165341.43389-1-espindola@scylladb.com>