Revert "net: Don't use variable length arrays"
This reverts commit 255ba91df684295d5745b4eb38326f1f4742876a. It
fails to build with --c++-dialect=gnu++14:

[1/1] Building CXX object CMakeFiles/seastar.dir/src/net/socket_address.cc.o
FAILED: CMakeFiles/seastar.dir/src/net/socket_address.cc.o
/usr/lib64/ccache/g++  -DFMT_SHARED -DSEASTAR_API_LEVEL=2 -DSEASTAR_HAS_MEMBARRIER -DSEASTAR_HAVE_ASAN_FIBER_SUPPORT -DSEASTAR_HAVE_GCC6_CONCEPTS -DSEASTAR_HAVE_HWLOC -DSEASTAR_HAVE_LZ4_COMPRESS_DEFAULT -DSEASTAR_HAVE_NUMA -DSEASTAR_THREAD_STACK_GUARDS -DSEASTAR_TYPE_ERASE_MORE -I../../include -Igen/include -I../../src -Igen/src -O1   -std=gnu++14 -U_FORTIFY_SOURCE -Wno-maybe-uninitialized -Wno-error=unused-result -fvisibility=hidden -UNDEBUG -Wall -Werror -Wno-error=deprecated-declarations -gz -fconcepts -MD -MT CMakeFiles/seastar.dir/src/net/socket_address.cc.o -MF CMakeFiles/seastar.dir/src/net/socket_address.cc.o.d -o CMakeFiles/seastar.dir/src/net/socket_address.cc.o -c ../../src/net/socket_address.cc
distcc[3474108] ERROR: compile ../../src/net/socket_address.cc on loki/3,lzo failed
../../src/net/socket_address.cc: In function 'std::string seastar::unix_domain_addr_text(const seastar::socket_address&)':
../../src/net/socket_address.cc:68:30: error: invalid conversion from 'const char*' to 'char*' [-fpermissive]