build: read non-ASCII DPDK config with correct encoding
The configure.py modifies the DPDK config file, which is a text file.
The code reads the file into a python string using the system's default
encoding, but the file contains several non-ASCII characters (trade mark and
registered-mark symbols) using UTF-8 encoding, so must be explicitly read
using that encoding, and not with the system's default encoding.

For example, with LC_CTYPE=he_IL (which uses the 8-bit encoding ISO-8859-8),
one gets the following error:

$ ./configure.py --enable-dpdk
...
Traceback (most recent call last):
  File "./configure.py", line 339, in <module>
    lines = open(dotconfig).readlines()
  File "/usr/lib64/python3.4/encodings/iso8859_8.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0xc2 in position 3402: character maps to <undefined>

Signed-off-by: Nadav Har'El <nyh@cloudius-systems.com>