build: bump yaml-cpp to 0.7.0 in cooking_recipe
* bump yaml-cpp from 0.5.3 to 0.7.0
* pass -DYAML_BUILD_SHARED_LIBS=ON when building yaml-cpp
  instead -DBUILD_SHARED_LIBS=ON
* drop the "REQUIRES Boost" option

this change is supposed to avoid build failure like:

In file included from /home/kefu/dev/seastar/build/debug/_cooking/ingredient/yaml-cpp/src/src/convert.cpp:3:
In file included from /home/kefu/dev/seastar/build/debug/_cooking/ingredient/yaml-cpp/src/include/yaml-cpp/node/convert.h:17:
In file included from /home/kefu/dev/seastar/build/debug/_cooking/ingredient/yaml-cpp/src/include/yaml-cpp/node/impl.h:11:
In file included from /home/kefu/dev/seastar/build/debug/_cooking/ingredient/yaml-cpp/src/include/yaml-cpp/node/iterator.h:13:
/var/ssd/ceph/src/seastar/build/debug/_cooking/ingredient/yaml-cpp/src/include/yaml-cpp/node/detail/iterator.h:48:54: error: no member named 'next' in namespace 'boost'
  void increment() { this->base_reference() = boost::next(this->base()); }
                                              ~~~~~~~^
1 error generated.

this is a known issue of yaml-cpp 5.x. it only surfaces when this
old version yaml-cpp is compiled with a relatively newer boost (v1.67.0
and up) which dropped boost::next(). this issue was fixed in yaml-cpp
v0.6.0, as it dropped the dependency on Boost.

after this change, the latest release of yaml-cpp is used, so we
are immune to this FTBFS issue.

Signed-off-by: Kefu Chai <tchaikov@gmail.com>