"git submodule" operation required before running configure.py
I got this when running configure.py on a freshly-cloned repository.

Notice: -fsanitize=vptr is broken, disabling; some debug mode tests are bypassed.
Notice: disabling -Wattributes due to https://gcc.gnu.org/bugzilla/show_bug.cgi?id=80947
Traceback (most recent call last):
  File "./configure.py", line 796, in <module>
    raise Exception(cares_dir + ' is empty. Run "git submodule update --init".')
Exception: c-ares is empty. Run "git submodule update --init".