map_reduce: do not move a temporary object
C++17 enforces copy ellision on prvalue like this, which is a temporary.
so there is no need to use `std::move()` here, moreover, it could
prevent the compiler from performing copy elision. and this hurts the
performance.

this change also silences warning like:
```
/home/kefu/dev/scylladb/seastar/include/seastar/core/map_reduce.hh:189:27: error: moving a temporary object prevents copy elision [-Werror=pessimizing-move]
/home/kefu/dev/scylladb/seastar/include/seastar/core/map_reduce.hh:189:27: note: remove ‘std::move’ call
```

Signed-off-by: Kefu Chai <kefu.chai@scylladb.com>