perftune.py: Fix nic_is_bond_iface() and other function signatures
Commit a2fc9d72c31b97840bc75ae49dbd6f4b6d394e25 introduced regression
causing the script to fail with following error:

  ERROR: nic_is_bond_iface() missing 1 required positional argument: 'nic'. Your system can't be tuned until the issue is fixed.

Fix the issue by removing the "@property" annotations, which replace the
function with a Python getter.

Acked-by: Lubos Kosco <lubos@scylladb.com>
Closes #852