net: replace deprecated ip::address_v4::from_string()
boost::asio::ip::address_v4::from_string() was removed in boost 1.87,
leading to compilation failures:

src/seastar/src/net/ip.cc:44:46: error: no member named 'from_string' in 'boost::asio::ip::address_v4'
    auto ipv4 = boost::asio::ip::address_v4::from_string(addr, ec);
                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^

prior to 1.87, the function had been documented as deprecated [1]:

> (Deprecated: Use make_address_v4().)

[1] https://www.boost.org/doc/libs/1_86_0/doc/html/boost_asio/reference/ip__address_v4/from_string.html

Signed-off-by: Casey Bodley <cbodley@redhat.com>

Closes scylladb/seastar#2610