Revert "queue: require element type to be nothrow move-constructible"
This reverts commit 471667ba1f83712b4d87b7bc71802a44e4afe954. Clang 12
complains in C++20 mode that the constraints on the class definition
and the out-of-line member function definitions are not equal:

/home/avi/scylla-maint/seastar/include/seastar/core/queue.hh:153:1: error: requires clause differs in template redeclaration
template <typename T>
^
/home/avi/scylla-maint/seastar/include/seastar/core/queue.hh:39:10: note: previous template declaration is here
requires std::is_nothrow_move_constructible_v<T>
         ^
/home/avi/scylla-maint/seastar/include/seastar/core/queue.hh:159:1: error: requires clause differs in template redeclaration
template <typename T>
^
/home/avi/scylla-maint/seastar/include/seastar/core/queue.hh:39:10: note: previous template declaration is here
requires std::is_nothrow_move_constructible_v<T>
         ^
/home/avi/scylla-maint/seastar/include/seastar/core/queue.hh:168:1: error: requires clause differs in template redeclaration
template <typename T>
^
/home/avi/scylla-maint/seastar/include/seastar/core/queue.hh:39:10: note: previous template declaration is here
requires std::is_nothrow_move_constructible_v<T>
         ^
/home/avi/scylla-maint/seastar/include/seastar/core/queue.hh:177:1: error: requires clause differs in template redeclaration
template <typename T>
^
/home/avi/scylla-maint/seastar/include/seastar/core/queue.hh:39:10: note: previous template declaration is here
requires std::is_nothrow_move_constructible_v<T>
         ^
/home/avi/scylla-maint/seastar/include/seastar/core/queue.hh:189:1: error: requires clause differs in template redeclaration
template <typename T>
^