build: use clang++ driver instead of clang
clang-5.0 does not link against C++'s standard library by default. so,
to address following errors show up in travis's build:

/home/travis/build/scylladb/seastar/fmt/test/posix-test.cc:(.text+0x1b0):
undefined reference to `std::string::_Rep::_S_empty_rep_storage'

we should instruct travis to use clang++ instead of clang.

Signed-off-by: Kefu Chai <tchaikov@gmail.com>