tests: do not capture unused variables
`this` is not used in some of these lambdas, so drop them. this
should address the warnings like

```
/home/circleci/project/tests/perf/shared_token_bucket.cc:227:22: error: lambda capture 'this' is not used [-Werror,-Wunused-lambda-capture]
        return work([this] (std::chrono::duration<double> d) {
                     ^
```

Signed-off-by: Kefu Chai <kefu.chai@scylladb.com>