net/tcp-stack: add forward declaration for seastar::socket
otherwise seastar::socket would be missing. and compiler might
fail with:

```
error: no type named 'socket' in namespace 'seastar'
```

Signed-off-by: Kefu Chai <kefu.chai@scylladb.com>