net: fix compilation problem introduced after e5cbee3
gcc 5.1.1 complains about the following:
/data/scylla/seastar/net/net.hh:134:45: error: invalid use of incomplete type ‘class net::device’
     uint16_t hw_queues_count() { return _dev->hw_queues_count(); }

Fix it by moving implementation of hw_queues_count() to net/net.cc

Signed-off-by: Raphael S. Carvalho <raphaelsc@scylladb.com>
Message-Id: <1455644668-27177-1-git-send-email-raphaelsc@scylladb.com>