util/tuple_utils.hh: avoid redundant move
per the resolution of https://wg21.link/cwg1148 , a move should be used
in this case: the parameter is an lvalue, but it's about to be
destroyed, so the compiler should consider it as an rvalue.

this change silences the warnings from GCC-10 and Clang-9 with
-Wredundant-move, like:

../src/seastar/include/seastar/util/tuple_utils.hh:34:23: warning:
redundant move in return statement [-Wredundant-move]
   34 |     return std::move(t);
      |                       ^
../src/seastar/include/seastar/util/tuple_utils.hh:34:23: note: remove
‘std::move’ call

and

error: redundant move in return statement [-Werror,-Wredundant-move]
  return std::move(t); // move used implicitly
         ^

Signed-off-by: Kefu Chai <kchai@redhat.com>
Message-Id: <20200214044000.2850108-1-tchaikov@gmail.com>