Revert "memory: always allocate buf using "malloc" for non reactor"
This reverts commit 2199ade2fa938f9d81f7eb7d52441c7023cabaa3. The build
bot complains:

../../src/core/memory.cc: In function 'void* seastar::memory::allocate(size_t)':
../../src/core/memory.cc:1353:16: error: '__libc_malloc' was not declared in this scope; did you mean 'hwloc_alloc'?
 1353 |         return __libc_malloc(size);
      |                ^~~~~~~~~~~~~
      |                hwloc_alloc
../../src/core/memory.cc: In function 'void* seastar::memory::allocate_aligned(size_t, size_t)':
../../src/core/memory.cc:1379:16: error: '__libc_posix_memalign' was not declared in this scope; did you mean '__builtin_posix_memalign'?
 1379 |         return __libc_posix_memalign(align, size);