weak_ptr: include used header
the missing include header was identifier by `ninja -C build/dev
checkheaders`:

```
FAILED: CMakeFiles/checkheaders-seastar.dir/checkheaders/include/seastar/core/weak_ptr.hh.cc.o
/home/kefu/.local/bin/clang++ -DBOOST_NO_CXX98_FUNCTION_BASE -DFMT_SHARED -DSEASTAR_API_LEVEL=7 -DSEASTAR_BUILD_SHARED_LIBS -DSEASTAR_DEFERRED_ACTION_REQUIRE_NOEXCEPT -DSEASTAR_ENABLE_ALLOC_FAILURE_INJECTION -DSEASTAR_HAS_MEMBARRIER -DSEASTAR_HAVE_ASAN_FIBER_SUPPORT -DSEASTAR_HAVE_HWLOC -DSEASTAR_HAVE_NUMA -DSEASTAR_HAVE_SYSTEMTAP_SDT -DSEASTAR_HAVE_URING -DSEASTAR_LOGGER_TYPE_STDOUT -DSEASTAR_PTHREAD_ATTR_SETAFFINITY_NP -DSEASTAR_SCHEDULING_GROUPS_COUNT=16 -DSEASTAR_SSTRING -DSEASTAR_STRERROR_R_CHAR_P -DSEASTAR_THREAD_STACK_GUARDS -DSEASTAR_TYPE_ERASE_MORE -Dcheckheaders_seastar_EXPORTS -I/home/kefu/dev/seastar/include/seastar/core -I/home/kefu/dev/seastar/include/seastar/util -I/home/kefu/dev/seastar/include/seastar/http -I/home/kefu/dev/seastar/include/seastar/json -I/home/kefu/dev/seastar/include/seastar/net -I/home/kefu/dev/seastar/include/seastar/rpc -I/home/kefu/dev/seastar/include/seastar/websocket -I/home/kefu/dev/seastar/src/core -I/home/kefu/dev/seastar/include -I/home/kefu/dev/seastar/build/dev/gen/include -I/home/kefu/dev/seastar/build/dev/gen/src -I/home/kefu/dev/seastar/src -O2 -std=gnu++20 -fPIC -U_FORTIFY_SOURCE -Wno-error=unused-result "-Wno-error=#warnings" -fstack-clash-protection -UNDEBUG -Wall -Werror -Wimplicit-fallthrough -Wdeprecated -Wno-error=deprecated -gz -Wno-unused-const-variable -Wno-unused-function -Wno-unused-variable -MD -MT CMakeFiles/checkheaders-seastar.dir/checkheaders/include/seastar/core/weak_ptr.hh.cc.o -MF CMakeFiles/checkheaders-seastar.dir/checkheaders/include/seastar/core/weak_ptr.hh.cc.o.d -o CMakeFiles/checkheaders-seastar.dir/checkheaders/include/seastar/core/weak_ptr.hh.cc.o -c /home/kefu/dev/seastar/build/dev/checkheaders/include/seastar/core/weak_ptr.hh.cc
/home/kefu/dev/seastar/build/dev/checkheaders/include/seastar/core/weak_ptr.hh.cc:59:9: error: no member named 'swap' in namespace 'std'; did you mean simply 'swap'?
        std::swap(_ptr, o._ptr);
        ^~~~~~~~~
        swap
/home/kefu/dev/seastar/build/dev/checkheaders/include/seastar/core/weak_ptr.hh.cc:57:10: note: 'swap' declared here
    void swap(weak_ptr&& o) noexcept {
         ^
/home/kefu/dev/seastar/build/dev/checkheaders/include/seastar/core/weak_ptr.hh.cc:70:14: error: no member named 'move' in namespace 'std'; did you mean 'boost::move'?
        swap(std::move(o));
             ^~~~~~~~~
             boost::move
/usr/include/boost/move/utility_core.hpp:212:93: note: 'boost::move' declared here
         BOOST_MOVE_FORCEINLINE typename ::boost::move_detail::remove_reference<T>::type && move(T&& t) BOOST_NOEXCEPT
                                                                                            ^
/home/kefu/dev/seastar/build/dev/checkheaders/include/seastar/core/weak_ptr.hh.cc:80:18: error: no member named 'move' in namespace 'std'; did you mean 'boost::move'?
            swap(std::move(o));
                 ^~~~~~~~~
                 boost::move
/usr/include/boost/move/utility_core.hpp:212:93: note: 'boost::move' declared here
         BOOST_MOVE_FORCEINLINE typename ::boost::move_detail::remove_reference<T>::type && move(T&& t) BOOST_NOEXCEPT
                                                                                            ^
3 errors generated.
```

in this change, the missing `#include` is added, so that `weak_ptr.hh`
is self-contained.

Signed-off-by: Kefu Chai <kefu.chai@scylladb.com>