prometheus: avoid ambiguity when calling MetricFamily.set_name()
in newer C++ language binding of protobuf, `ArenaStringPtr::Set()`
accepts both `std::string` and `std::string_view`, while the C++
lanaguage binding genereated by protoc just fowrard the type of the
parameter, so if the parameter is a `sstring`, we would run into
FTBFS like

```
seastar/build/release/gen/src/proto/metrics2.pb.h:2891:20: error: call of overloaded ‘Set(const seastar::basic_sstring<char, unsigned int, 15>&, google::protobuf::Arena*)’ is ambiguous
 2891 |   _impl_.value_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
      |   ~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/include/google/protobuf/arenastring.h:478:22: note: candidate: ‘void google::protobuf::internal::ArenaStringPtr::Set(const std::string&, google::protobuf::Arena*) [with OverloadDisambiguator = {}; std::string = std::__cxx11::basic_string<char>]’
  478 | PROTOBUF_EXPORT void ArenaStringPtr::Set(const std::string& value,
      |                      ^~~~~~~~~~~~~~
/usr/include/google/protobuf/arenastring.h:295:8: note: candidate: ‘void google::protobuf::internal::ArenaStringPtr::Set(absl::lts_20230802::string_view, google::protobuf::Arena*)’
  295 |   void Set(absl::string_view value, Arena* arena);
      |        ^~~
/usr/include/google/protobuf/arenastring.h:296:8: note: candidate: ‘void google::protobuf::internal::ArenaStringPtr::Set(std::string&&, google::protobuf::Arena*)’
  296 |   void Set(std::string&& value, Arena* arena);
```

so avoid the ambiguity, let's use `fmt::format()` to set the metric
family's name, as `fmt::format()` returns an `std::string`. and
at the other caller sites, cast `sstring` to `std::string` instead.
please note, in the older protobuf's C++ binding header files,
the setters only accept `std::string`, so to be backward compatible,
`std::string` is used instead of `std::string_view`.

Fixes #2111
Signed-off-by: Kefu Chai <kefu.chai@scylladb.com>