Revert "Merge: Refine COUNTER metrics"
This reverts commit 7fff41fd266a00538ee14e7eff99efb4833f0c51, reversing
changes made to e874acefc326ed63c447b0e3edeebf5d784ce794. It does not
build in C++17 mode:

/usr/bin/g++ -DFMT_LOCALE -DFMT_SHARED -DSEASTAR_API_LEVEL=6 -DSEASTAR_DEFERRED_ACTION_REQUIRE_NOEXCEPT -DSEASTAR_HAS_MEMBARRIER -DSEASTAR_HAVE_ASAN_FIBER_SUPPORT -DSEASTAR_HAVE_HWLOC -DSEASTAR_HAVE_LZ4_COMPRESS_DEFAULT -DSEASTAR_HAVE_NUMA -DSEASTAR_SCHEDULING_GROUPS_COUNT=16 -I../../include -Igen/include -O2 -g -DNDEBUG -fvisibility=hidden -UNDEBUG -Wall -Werror -Wno-array-bounds -Wno-error=deprecated-declarations -gz -std=c++17 -U_FORTIFY_SOURCE -Wno-maybe-uninitialized -DSEASTAR_SSTRING -Wno-error=unused-result -MD -MT CMakeFiles/seastar_perf_testing.dir/tests/perf/perf_tests.cc.o -MF CMakeFiles/seastar_perf_testing.dir/tests/perf/perf_tests.cc.o.d -o CMakeFiles/seastar_perf_testing.dir/tests/perf/perf_tests.cc.o -c ../../tests/perf/perf_tests.cc
In file included from ../../include/seastar/core/metrics_api.hh:24,
                 from ../../include/seastar/core/app-template.hh:30,
                 from ../../tests/perf/perf_tests.cc:33:
../../include/seastar/core/metrics.hh:263:161: error: 'type_identity' in namespace 'std' does not name a template type