noncopyable_function: disable -Wuninitialized warning in noncopyable_function_base
The compiler (gcc 9.2.1/Fedora 31) complains about uninitialized
"noncopyable_function_base::_storage::direct[0]" usage in
"noncopyable_function_base::trivial_direct_move" function.

For example, this behavior is triggered in the situations where a stateless
lambda (i.e. trivially copyable) is used while move-initializing a
noncopyable_function class instance out of it:

<work_dir>/scylla/seastar/include/seastar/util/noncopyable_function.hh:58:36: error:
'<anonymous>.seastar::internal::noncopyable_function_base::_storage.seastar::internal::noncopyable_function_base::storage::direct[0]' is used uninitialized in this function [-Werror=uninitialized]
   58 |             to->_storage.direct[i] = from->_storage.direct[i];

Clang 9 compiles without errors in that case, so disable the bogus
warning for GCC.

Signed-off-by: Pavel Solodovnikov <pa.solodovnikov@scylladb.com>
Message-Id: <20191128145842.663426-1-pa.solodovnikov@scylladb.com>