on_internal_error: add noexcept variant
Usable in noexcept environments like destructors and noexcept functions.
This variant doesn't throw, by default it just logs the error, and if
the flag is set also aborts.

Signed-off-by: Botond Dénes <bdenes@scylladb.com>
Message-Id: <20200924134649.399705-1-bdenes@scylladb.com>