build: fix dpdk library link order
The eal library refers to symbols in the kvargs library, so it has to come before.
This fixes build errors due to unresolved symbols:

/home/avi/scylla/seastar/build/dev/_cooking/installed/lib/librte_eal.a(eal_common_devargs.o):eal_common_devargs.c:function rte_devargs_layers_parse: error: undefined reference to 'rte_kvargs_parse_delim'
/home/avi/scylla/seastar/build/dev/_cooking/installed/lib/librte_eal.a(eal_common_devargs.o):eal_common_devargs.c:function rte_devargs_layers_parse: error: undefined reference to 'rte_kvargs_free'
collect2: error: ld returned 1 exit status

Seastar's executables build before and after this patch; I don't
know why the problem only affects external executables.
Message-Id: <20190630121458.2728-1-avi@scylladb.com>